name: Push Docker Image

on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - 'v*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Lowercased repo owner
        id: login
        run: |
          echo "LOWERCASE_OWNER=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
        shell: bash
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to docker
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_PAT }}
      - name: Extract Git Tags
        id: extract_tags
        run: |
          tags=$(git tag --contains $(git rev-parse HEAD) | tr '\n' ',' | sed 's/,$//')
          if [ -z "$tags" ]; then
            tags="latest"
          fi
          echo "tags=$tags" >> $GITHUB_ENV
      - name: Get Commit SHA
        id: get_sha
        run: echo "sha=${GITHUB_SHA}" >> $GITHUB_ENV
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          push: true
          context: .
          tags: |
            ghcr.io/${{ env.LOWERCASE_OWNER }}/flask-app-api:latest
            ghcr.io/${{ env.LOWERCASE_OWNER }}/flask-app-api:${{ env.sha }}
            ghcr.io/${{ env.LOWERCASE_OWNER }}/flask-app-api:${{ env.tags }}
      - name: Logout from ghcr.io
        run: docker logout ghcr.io